---
appName: splunk-arcade
arcadeHost: splunk-arcade.home

# when unset openai integration is simply disabled
openaiApiKey: ""

# used to clear incidents that we receive on the inbound webhook from observability cloud
observabilityApiAccessToken: ""

ingress-nginx:
  enabled: true
  namespaceOverride: ingress-nginx

redis:
  auth:
    enabled: false
  persistence:
    # we just use this as a session cache, so probably not really needed to have
    # persistence
    enabled: false

postgresql:
  architecture: standalone
  auth:
    enablePostgresUser: true
    password: "password"
    database: "myapp"
  primary:
    resourcesPreset: "medium"
    # https://stackoverflow.com/questions/30778015/how-to-increase-the-max-connections-in-postgres/32584211#32584211
    # https://stackoverflow.com/questions/73218618/bitnami-postgresql-change-max-connections
    extraEnvVars:
      - name: POSTGRESQL_MAX_CONNECTIONS
        value: "400"

  readReplicas:
    resourcesPreset: "small"
    extraEnvVars:
      # postgres gets v mad if not same as primary
      - name: POSTGRESQL_MAX_CONNECTIONS
        value: "400"

tls:
  enabled: false
  secret_name: splunk-arcade-tls

splunk-otel-collector:
  clusterName: gamify
  environment: gamify
  agent:
    discovery:
      enabled: true
    config:
      receivers:
        hostmetrics:
          scrapers:
            filesystem:
              exclude_mount_points:
                match_type: regexp
                mount_points:
                  - /var/*
                  - /snap/*
                  - /boot/*
                  - /boot
                  - /opt/orbstack/*
                  - /mnt/machines/*
                  - /Users/*
  gateway:
    enabled: false
  splunkPlatform:
    endpoint: https://127.0.0.1:8088/services/collector
    token: REPLACE_ME
    index: splunk-arcade
  splunkObservability:
    realm: us1
    accessToken: REPLACE_ME
    logsEnabled: true
    profilingEnabled: true
  extraAttributes:
    fromLabels:
      - key_regex: (.*)
        from: pod
        tag_name: "$$1"

scoreboard:
  image: splunk-arcade/scoreboard:latest
  imagePullPolicy: Always
  replicaCount: 1
  resources:
    requests:
      memory: 128Mi
      cpu: 50m
    limits:
      memory: 512Mi
      cpu: 500m

portal:
  image: splunk-arcade/portal:latest
  imagePullPolicy: Always
  replicaCount: 1
  resources:
    requests:
      memory: 128Mi
      cpu: 50m
    limits:
      memory: 512Mi
      cpu: 500m

playerRouter:
  image: splunk-arcade/player-router:latest
  imagePullPolicy: Always
  replicaCount: 3
  resources:
    requests:
      memory: 128Mi
      cpu: 250m
    limits:
      memory: 512Mi
      cpu: 500m

cabinet:
  image: splunk-arcade/cabinet:latest
  imagePullPolicy: Always
  replicaCount: 1
  resources:
    requests:
      memory: 128Mi
      cpu: 250m
    limits:
      memory: 512Mi
      cpu: 500m

playerContent:
  image: splunk-arcade/player-content:latest
  imagePullPolicy: Always
  replicaCount: 1
  resources:
    requests:
      memory: 128Mi
      cpu: 250m
    limits:
      memory: 512Mi
      cpu: 500m

playerCloud:
  image: splunk-arcade/player-cloud:latest
  imagePullPolicy: Always

# only used for dev on cabinet, otherwise spawn player cabinets via registration portal
players: []
