---
version: v2beta1
name: splunk-arcade-scoreboard

vars:
  DEVSPACE_FLAGS: "-n splunk-arcade"

  SPLUNK_ARCADE_REGISTRY:
    source: env
    default: splunk-arcade

  SPLUNK_ARCADE_LOCAL_REGISTRY_ENABLED:
    source: env
    default: true

  SPLUNK_ARCADE_OBSERVABILITY_ENV:
    source: env
    default: gameify

  SPLUNK_ARCADE_OBSERVABILITY_REALM:
    source: env
    default: us1

  SPLUNK_ARCADE_OBSERVABILITY_ACCESS_TOKEN:
    source: env
    default: REPLACE_ME

  SPLUNK_ARCADE_PLATFORM_ENDPOINT:
    source: env
    default: https://127.0.0.1:8088/services/collector

  SPLUNK_ARCADE_PLATFORM_TOKEN:
    source: env
    default: REPLACE_ME

  SPLUNK_ARCADE_OBSERVABILITY_API_ACCESS_TOKEN:
    source: env
    default: REPLACE_ME

  SPLUNK_ARCADE_OPENAI_API_KEY:
    source: env
    default: ""

  IMAGE_PULL_POLICY: Always
  CABINET_IMAGE: ${SPLUNK_ARCADE_REGISTRY}/cabinet
  SCOREBOARD_IMAGE: ${SPLUNK_ARCADE_REGISTRY}/scoreboard
  PORTAL_IMAGE: ${SPLUNK_ARCADE_REGISTRY}/portal
  PLAYER_CONTENT_IMAGE: ${SPLUNK_ARCADE_REGISTRY}/player-content
  PLAYER_ROUTER_IMAGE: ${SPLUNK_ARCADE_REGISTRY}/player-router
  PY_IMAGE_DEV: ${SPLUNK_ARCADE_REGISTRY}/py-dev
  GO_IMAGE_DEV: ${SPLUNK_ARCADE_REGISTRY}/go-dev

  VERSION: 0.0.0
  COMMIT_HASH: $(git describe --always --abbrev=8)

localRegistry:
  enabled: ${SPLUNK_ARCADE_LOCAL_REGISTRY_ENABLED}

images:
  py-dev:
    createPullSecret: false
    image: ${PY_IMAGE_DEV}
    context: ./
    dockerfile: ./dev.py.Dockerfile
    rebuildStrategy: ignoreContextChanges
    tags:
      - ${COMMIT_HASH}

  go-dev:
    createPullSecret: false
    image: ${GO_IMAGE_DEV}
    context: ./
    dockerfile: ./dev.go.Dockerfile
    rebuildStrategy: ignoreContextChanges
    tags:
      - ${COMMIT_HASH}

  cabinet:
    createPullSecret: false
    image: ${CABINET_IMAGE}
    context: ./cabinet
    dockerfile: ./cabinet/Dockerfile
    rebuildStrategy: ignoreContextChanges
    tags:
      - latest
      - ${COMMIT_HASH}

  scoreboard:
    createPullSecret: false
    image: ${SCOREBOARD_IMAGE}
    context: ./scoreboard
    dockerfile: ./scoreboard/Dockerfile
    rebuildStrategy: ignoreContextChanges
    tags:
      - latest
      - ${COMMIT_HASH}

  portal:
    createPullSecret: false
    image: ${PORTAL_IMAGE}
    context: ./portal
    dockerfile: ./portal/Dockerfile
    rebuildStrategy: ignoreContextChanges
    tags:
      - latest
      - ${COMMIT_HASH}

  player-content:
    createPullSecret: false
    image: ${PLAYER_CONTENT_IMAGE}
    context: ./player-content
    dockerfile: ./player-content/Dockerfile
    rebuildStrategy: ignoreContextChanges
    tags:
      - latest
      - ${COMMIT_HASH}

  player-router:
    createPullSecret: false
    image: ${PLAYER_ROUTER_IMAGE}
    context: ./player-router
    dockerfile: ./player-router/Dockerfile
    rebuildStrategy: ignoreContextChanges
    tags:
      - latest
      - ${COMMIT_HASH}

deployments:
  splunk-arcade:
    helm:
      displayOutput: true
      chart:
        name: ./chart/
      values:
        openaiApiKey: ${SPLUNK_ARCADE_OPENAI_API_KEY}
        observabilityApiAccessToken: ${SPLUNK_ARCADE_OBSERVABILITY_API_ACCESS_TOKEN}
        splunk-otel-collector:
          environment: ${SPLUNK_ARCADE_OBSERVABILITY_ENV}
          splunkObservability:
            realm: ${SPLUNK_ARCADE_OBSERVABILITY_REALM}
            accessToken: ${SPLUNK_ARCADE_OBSERVABILITY_ACCESS_TOKEN}
          splunkPlatform:
            endpoint: ${SPLUNK_ARCADE_PLATFORM_ENDPOINT}
            token: ${SPLUNK_ARCADE_PLATFORM_TOKEN}
        cabinet:
          image: ${CABINET_IMAGE}
          imagePullPolicy: ${IMAGE_PULL_POLICY}
        scoreboard:
          image: ${SCOREBOARD_IMAGE}
          imagePullPolicy: ${IMAGE_PULL_POLICY}
        portal:
          image: ${PORTAL_IMAGE}
          imagePullPolicy: ${IMAGE_PULL_POLICY}
        player-content:
          image: ${PLAYER_CONTENT_IMAGE}
          imagePullPolicy: ${IMAGE_PULL_POLICY}
        playerRouter:
          image: ${PLAYER_ROUTER_IMAGE}
          imagePullPolicy: ${IMAGE_PULL_POLICY}

dev:
  splunk-arcade:
    labelSelector:
      app.kubernetes.io/name: splunk-arcade-cabinet
    devImage: ${CABINET_IMAGE_DEV}
    sync:
      - path: ./cabinet/:/app
        disableDownload: true
        excludeFile: .dockerignore
    terminal:
      command: ./start-dev.sh
    ports:
    - port: "8080:5000"

profiles:
  - name: prod
    patches:
      # persistence for prod in case registry dies for whatever reason
      - op: add
        path: localRegistry.persistence
        value:
          enabled: true
          size: 10Gi
      # prod host + tls ofc
      - op: add
        path: deployments.splunk-arcade.helm.values.arcadeHost
        value: www.splunkarcade.com
      - op: add
        path: deployments.splunk-arcade.helm.values.tls
        value:
          enabled: true
      # crank up some replicas for things for prod
      - op: add
        path: deployments.splunk-arcade.helm.values.scoreboard.replicaCount
        value: 3
      - op: add
        path: deployments.splunk-arcade.helm.values.portal.replicaCount
        value: 3
      - op: add
        path: deployments.splunk-arcade.helm.values.playerRouter.replicaCount
        value: 5
      - op: add
        path: deployments.splunk-arcade.helm.values.playerContent.replicaCount
        value: 3
      # set to IfNotPresent for image pull for prod
      - op: replace
        path: deployments.splunk-arcade.helm.values.scoreboard.imagePullPolicy
        value: IfNotPresent
      - op: replace
        path: deployments.splunk-arcade.helm.values.portal.imagePullPolicy
        value: IfNotPresent
      - op: replace
        path: deployments.splunk-arcade.helm.values.playerRouter.imagePullPolicy
        value: IfNotPresent
      - op: replace
        path: deployments.splunk-arcade.helm.values.playerContent.imagePullPolicy
        value: IfNotPresent
      # ensure we always use tagged version for the real deal
      - op: replace
        path: images.cabinet.tags
        value:
          - ${COMMIT_HASH}
      - op: replace
        path: images.scoreboard.tags
        value:
          - ${COMMIT_HASH}
      - op: replace
        path: images.portal.tags
        value:
          - ${COMMIT_HASH}
      - op: replace
        path: images.player-content.tags
        value:
          - ${COMMIT_HASH}
      - op: replace
        path: images.player-router.tags
        value:
          - ${COMMIT_HASH}

  - name: dev-cabinet
    patches:
      - op: add
        path: deployments.splunk-arcade.helm.values.players
        value:
          - devplayer
      - op: replace
        path: dev
        value:
          splunk-arcade:
            labelSelector:
              app.kubernetes.io/name: splunk-arcade-cabinet
            devImage: ${PY_IMAGE_DEV}
            sync:
              - path: ./cabinet/:/app
                disableDownload: true
                excludeFile: .dockerignore
            terminal:
              command: ./start-dev.sh
            ports:
              - port: "8080:5000"

  - name: dev-player-router
    patches:
      - op: add
        path: deployments.splunk-arcade.helm.values.players
        value:
          - devplayer
      - op: add
        path: deployments.splunk-arcade.helm.values.playerRouter.replicaCount
        value: 1
      - op: replace
        path: dev
        value:
          splunk-arcade:
            labelSelector:
              app.kubernetes.io/name: splunk-arcade-player-router
            devImage: ${GO_IMAGE_DEV}
            sync:
              - path: ./player-router/:/app
                disableDownload: true
                excludeFile: .dockerignore
            terminal:
              command: ./start-dev.sh
            ports:
              - port: "8080:5000"

  - name: dev-scoreboard
    patches:
      - op: replace
        path: dev
        value:
          splunk-arcade:
            labelSelector:
              app.kubernetes.io/name: splunk-arcade-scoreboard
            devImage: ${PY_IMAGE_DEV}
            sync:
              - path: ./scoreboard/:/app
                disableDownload: true
                excludeFile: .dockerignore
            terminal:
              command: ./start-dev.sh
            ports:
              - port: "8080:5000"

  - name: dev-portal
    patches:
      - op: replace
        path: dev
        value:
          splunk-arcade:
            labelSelector:
              app.kubernetes.io/name: splunk-arcade-portal
            devImage: ${PY_IMAGE_DEV}
            sync:
              - path: ./portal/:/app
                disableDownload: true
                excludeFile: .dockerignore
            terminal:
              command: ./start-dev.sh
            ports:
              - port: "8080:5000"

  - name: dev-player-content
    patches:
      - op: replace
        path: dev
        value:
          splunk-arcade:
            labelSelector:
              app.kubernetes.io/name: splunk-arcade-player-content
            devImage: ${PY_IMAGE_DEV}
            sync:
              - path: ./player-content/:/app
                disableDownload: true
                excludeFile: .dockerignore
            terminal:
              command: ./start-dev.sh
            ports:
              - port: "8080:5000"

pipelines:
  # override the default purge pipeline so we can nuke registry too
  purge:
    run: |-
      stop_dev --all
      purge_deployments --all
      kubectl delete deployments -n ${DEVSPACE_NAMESPACE} registry || true
      kubectl delete statefulsets -n ${DEVSPACE_NAMESPACE} registry || true
      kubectl delete pvc -n ${DEVSPACE_NAMESPACE} registry-registry-0 || true
